version: "3.8"

services:
  app:
    image: spira-training:latest
    build:
      context: .
    volumes:
      - .:/app
      - /app/.venv
    
  unit-tests:
    image: spira-training:latest
    build:
      context: .
    command: "poetry run pytest tests/unit"
    volumes:
      - .:/app
      - /app/.venv
      
  integration-tests:
    image: spira-training:latest
    build:
      context: .
    command: "poetry run pytest tests/integration"
    volumes:
      - .:/app
      - /app/.venv
      
