version: "3.8"

services:
  app:
    build:
      context: .
    volumes:
      - .:/app
      - /app/.venv
    
  tests:
    build:
      context: .
    command: "poetry run pytest"
    volumes:
      - .:/app
      - /app/.venv
      
