version: "3.8"

services:
  app:
    image: spira-training:0.0.1
    build:
      context: .
    volumes:
      - .:/app
      - /app/.venv
    
  tests:
    image: spira-training:0.0.1
    build:
      context: .
    command: "poetry run pytest"
    volumes:
      - .:/app
      - /app/.venv
      
