[tool.poetry]
name = "spira-training"
version = "0.1.0"
description = ""
authors = ["Roberto Bolgheroni <robertobolgheroni@usp.br>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
